# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
nb:
  languageCode:  nb
  contentDir: content/nb
  params:
    description: Friluftsterapi
  menu:
    - name: ABUP
      url: www.abup.no
      weight: 1
    - name: Om oss
      url: '#about'
      weight: 2
    - name: Nyheter
      url: '#news'

en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  title: Outdoors Therapy
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1


