# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
nb:
  languageCode:  nb
  contentDir: content/nb

en:
  languageCode: en-us
   # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  title: Outdoors Therapy
  contentDir: content/en
  params:
   description: Site description in English...
  menu:
   main:
  - name: ABUP FoU
    url: www.abup.no
    weight: 1
  - name: About
    url: about
    weight: 10
  - name: Our Team
    url: people
    weight: 20
  - name: News
    url: post
    weight: 30
  - name: Events
    url: event
    weight: 40
  - name: Publications/media
    url: publication
    weight: 50
  - name: Contact us
    url: contact
    weight: 60
  - name: Gallery
    url: https://www.instagram.com/abupagder/?hl=nb
    weight: 70



# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1


